/// Flutter icons CommerceIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CommerceIcons
///      fonts:
///       - asset: fonts/CommerceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CommerceIcons {
  CommerceIcons._();

  static const _kFontFam = 'CommerceIcons';
  static const String? _kFontPkg = null;

  static const IconData cartE = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filterE = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear_settingE = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gemE = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hangerE = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartE = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeE = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboardE = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sportE = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trashE = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tri_dotsE = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData userE = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
